export {
  DEFAULT_PAGE_SIZE,
  MAX_PAGE_SIZE,
  normalizePagination,
  toPaginated,
  type Paginated,
  type PaginationInput,
} from "./pagination";

export {
  apiFail,
  apiOk,
  type ApiError,
  type ApiErrorCategory,
  type ApiFailure,
  type ApiResult,
  type ApiSuccess,
} from "./result";

export type {
  CategoryPublicApi,
  CompanyPublicApi,
  ContactPublicApi,
  DeparturePublicApi,
  DestinationPublicApi,
  EnquiryAdminApi,
  EnquiryListFilters,
  EnquiryPublicApi,
  FaqListFilters,
  FaqPublicApi,
  GalleryListFilters,
  GalleryPublicApi,
  HomepagePayload,
  HomepagePublicApi,
  LegalPublicApi,
  NavigationPublicApi,
  PackageDetail,
  PackageListFilters,
  PackagePublicApi,
  PublicCatalogApi,
  SocialLinksPublicApi,
  TestimonialListFilters,
  TestimonialPublicApi,
  TourManagerPublicApi,
} from "./resources";
